export const ANALYSIS_FETCH_STARTED = 'ANALYSIS_FETCH_STARTED';
export const ANALYSIS_FETCH_COMPLETED = 'ANALYSIS_FETCH_COMPLETED';
export const ANALYSIS_FETCH_FAILED = 'ANALYSIS_FETCH_FAILED';

export const ANALYSIS_ADD_STARTED = 'ANALYSIS_ADD_STARTED';
export const ANALYSIS_ADD_COMPLETED = 'ANALYSIS_ADD_COMPLETED';
export const ANALYSIS_ADD_FAILED = 'ANALYSIS_ADD_FAILED';

export const ANALYSIS_REMOVE_STARTED = 'ANALYSIS_REMOVE_STARTED';
export const ANALYSIS_REMOVE_COMPLETED = 'ANALYSIS_REMOVE_COMPLETED';
export const ANALYSIS_REMOVE_FAILED = 'ANALYSIS_REMOVE_FAILED';
