export const AUTHOR_FETCH_STARTED = 'AUTHOR_FETCH_STARTED';
export const AUTHOR_FETCH_COMPLETED = 'AUTHOR_FETCH_COMPLETED';
export const AUTHOR_FETCH_FAILED = 'AUTHOR_FETCH_FAILED';

export const AUTHOR_ADD_STARTED = 'AUTHOR_ADD_STARTED';
export const AUTHOR_ADD_COMPLETED = 'AUTHOR_ADD_COMPLETED';
export const AUTHOR_ADD_FAILED = 'AUTHOR_ADD_FAILED';

export const AUTHOR_REMOVE_STARTED = 'AUTHOR_REMOVE_STARTED';
export const AUTHOR_REMOVE_COMPLETED = 'AUTHOR_REMOVE_COMPLETED';
export const AUTHOR_REMOVE_FAILED = 'AUTHOR_REMOVE_FAILED';

export const AUTHOR_SELECTED = 'AUTHOR_SELECTED';
export const AUTHOR_DESELECTED = 'AUTHOR_DESELECTED';

export const AUTHOR_BOOKS_FETCH_STARTED = 'AUTHOR_BOOKS_FETCH_STARTED';
export const AUTHOR_BOOKS_FETCH_COMPLETED = 'AUTHOR_BOOKS_FETCH_COMPLETED';
export const AUTHOR_BOOKS_FETCH_FAILED = 'AUTHOR_BOOKS_FETCH_FAILED';