export const BOOK_FETCH_STARTED = 'BOOK_FETCH_STARTED';
export const BOOK_FETCH_COMPLETED = 'BOOK_FETCH_COMPLETED';
export const BOOK_FETCH_FAILED = 'BOOK_FETCH_FAILED';

export const BOOK_ADD_STARTED = 'BOOK_ADD_STARTED';
export const BOOK_ADD_COMPLETED = 'BOOK_ADD_COMPLETED';
export const BOOK_ADD_FAILED = 'BOOK_ADD_FAILED';

export const BOOK_REMOVE_STARTED = 'BOOK_REMOVE_STARTED';
export const BOOK_REMOVE_COMPLETED = 'BOOK_REMOVE_COMPLETED';
export const BOOK_REMOVE_FAILED = 'BOOK_REMOVE_FAILED';

export const BOOK_SELECTED = 'BOOK_SELECTED';
export const BOOK_DESELECTED = 'BOOK_DESELECTED';
