export const CART_ITEM_ADDED = 'CART_ITEM_ADDED';
export const CART_ITEM_ADDED_CONFIRMED = 'CART_ITEM_ADDED_CONFIRMED';

export const CART_ITEM_MODIFIED = 'CART_ITEM_MODIFIED';

export const CART_ITEM_REMOVED = 'CART_ITEM_REMOVED';
export const CART_ITEM_REMOVED_CONFIRMED = 'CART_ITEM_REMOVED_CONFIRMED';

export const CODE_USED = 'CODE_USED';
export const CODE_APPROVED = 'CODE_APPROVED';
export const CODE_REJECTED = 'CODE_REJECTED';

export const CART_CLEARED = 'CART_CLEARED';
export const CART_CLEARED_CONFIRMED = 'CART_CLEARED_CONFIRMED'

export const CART_CHECKOUT = 'CART_CHECKOUT';
export const CART_USER_CHECK = 'CART_USER_CHECK';
export const CART_USER_CONFIRMED = 'CART_USER_CONFIRMED';
export const CART_USER_DENIED = 'CART_USER_DENIED';

export const CART_FETCH_STARTED = 'CART_FETCHED_STARTED';
export const CART_FETCH_CONFIRMED = 'CART_FETCH_CONFIRMED';

export const CART_CHECKOUT_STARTED = 'CART_CHECKOUT_STARTED';
export const CART_CHECKOUT_COMPLETED = 'CART_CHECKOUT_COMPLETED';
export const CART_CHECKOUT_REJECTED = 'CART_CHECKOUT_REJECTED';

export const CART_GIFT_STARTED = 'CART_GIFT_STARTED';
export const CART_GIFT_COMPLETED = 'CART_GIFT_COMPLETED';
export const CART_GIFT_REJECTED = 'CART_GIFT_REJECTED';