export const NOTE_FETCH_STARTED = 'NOTE_FETCH_STARTED';
export const NOTE_FETCH_COMPLETED = 'NOTE_FETCH_COMPLETED';
export const NOTE_FETCH_FAILED = 'NOTE_FETCH_FAILED';

export const NOTE_ADD_STARTED = 'NOTE_ADD_STARTED';
export const NOTE_ADD_COMPLETED = 'NOTE_ADD_COMPLETED';
export const NOTE_ADD_FAILED = 'NOTE_ADD_FAILED';

export const NOTE_REMOVE_STARTED = 'NOTE_REMOVE_STARTED';
export const NOTE_REMOVE_COMPLETED = 'NOTE_REMOVE_COMPLETED';
export const NOTE_REMOVE_FAILED = 'NOTE_REMOVE_FAILED';

export const NOTE_SELECTED = 'NOTE_SELECTED';
export const NOTE_DESELECTED = 'NOTE_DESELECTED';
