export const PUBLISHER_FETCH_STARTED = 'PUBLISHER_FETCH_STARTED';
export const PUBLISHER_FETCH_COMPLETED = 'PUBLISHER_FETCH_COMPLETED';
export const PUBLISHER_FETCH_FAILED = 'PUBLISHER_FETCH_FAILED';

export const PUBLISHER_SELECTED = 'PUBLISHER_SELECTED';
export const PUBLISHER_DESELECTED = 'PUBLISHER_DESELECTED';

export const PUBLISHER_BOOKS_FETCH_STARTED = 'PUBLISHER_BOOKS_FETCH_STARTED';
export const PUBLISHER_BOOKS_FETCH_COMPLETED = 'PUBLISHER_BOOKS_FETCH_COMPLETED';
export const PUBLISHER_BOOKS_FETCH_FAILED = 'PUBLISHER_BOOKS_FETCH_FAILED';