export const REVIEW_FETCH_STARTED = 'REVIEW_FETCH_STARTED';
export const REVIEW_FETCH_COMPLETED = 'REVIEW_FETCH_COMPLETED';
export const REVIEW_FETCH_FAILED = 'REVIEW_FETCH_FAILED';

export const REVIEW_ADD_STARTED = 'REVIEW_ADD_STARTED';
export const REVIEW_ADD_COMPLETED = 'REVIEW_ADD_COMPLETED';
export const REVIEW_ADD_FAILED = 'REVIEW_ADD_FAILED';

export const REVIEW_REMOVE_STARTED = 'REVIEW_REMOVE_STARTED';
export const REVIEW_REMOVE_COMPLETED = 'REVIEW_REMOVE_COMPLETED';
export const REVIEW_REMOVE_FAILED = 'REVIEW_REMOVE_FAILED';

export const REVIEW_SELECTED = 'REVIEW_SELECTED';
export const REVIEW_DESELECTED = 'REVIEW_DESELECTED';

export const REVIEW_FOR_BOOK_FETCH_STARTED = 'REVIEW_FOR_BOOK_FETCH_STARTED';
export const REVIEW_FOR_BOOK_FETCH_COMPLETED = 'REVIEW_FOR_BOOK_FETCH_COMPLETED';
export const REVIEW_FOR_BOOK_FETCH_FAILED = 'REVIEW_FETCH_FAILED';