export const SERIES_FETCH_STARTED = 'SERIES_FETCH_STARTED';
export const SERIES_FETCH_COMPLETED = 'SERIES_FETCH_COMPLETED';
export const SERIES_FETCH_FAILED = 'SERIES_FETCH_FAILED';

export const SERIES_ADD_STARTED = 'SERIES_ADD_STARTED';
export const SERIES_ADD_COMPLETED = 'SERIES_ADD_COMPLETED';
export const SERIES_ADD_FAILED = 'SERIES_ADD_FAILED';

export const SERIES_REMOVE_STARTED = 'SERIES_REMOVE_STARTED';
export const SERIES_REMOVE_COMPLETED = 'SERIES_REMOVE_COMPLETED';
export const SERIES_REMOVE_FAILED = 'SERIES_REMOVE_FAILED';
