export const SESSION_FETCH_STARTED = 'SESSION_FETCH_STARTED';
export const SESSION_FETCH_COMPLETED = 'SESSION_FETCH_COMPLETED';
export const SESSION_FETCH_FAILED = 'SESSION_FETCH_FAILED';

export const SESSION_ADD_STARTED = 'SESSION_ADD_STARTED';
export const SESSION_ADD_COMPLETED = 'SESSION_ADD_COMPLETED';
export const SESSION_ADD_FAILED = 'SESSION_ADD_FAILED';

export const SESSION_REMOVE_STARTED = 'SESSION_REMOVE_STARTED';
export const SESSION_REMOVE_COMPLETED = 'SESSION_REMOVE_COMPLETED';
export const SESSION_REMOVE_FAILED = 'SESSION_REMOVE_FAILED';

export const SESSION_SELECTED = 'SESSION_SELECTED';
export const SESSION_DESELECTED = 'SESSION_DESELECTED';