export const TRANSACTION_FETCH_STARTED = 'TRANSACTION_FETCH_STARTED';
export const TRANSACTION_FETCH_COMPLETED = 'TRANSACTION_FETCH_COMPLETED';
export const TRANSACTION_FETCH_FAILED = 'TRANSACTION_FETCH_FAILED';

export const OWN_BOOKS_FETCH_STARTED = 'OWN_BOOKS_FETCH_STARTED';
export const OWN_BOOKS_FETCH_COMPLETED = 'OWN_BOOKS_FETCH_COMPLETED';
export const OWN_BOOKS_FETCH_FAILED = 'OWN_BOOKS_FETCH_FAILED';

export const READ_BOOK = 'READ_BOOK';

export const TRANSACTION_ADD_STARTED = 'TRANSACTION_ADD_STARTED';
export const TRANSACTION_ADD_COMPLETED = 'TRANSACTION_ADD_COMPLETED';
export const TRANSACTION_ADD_FAILED = 'TRANSACTION_ADD_FAILED';

export const TRANSACTION_REMOVE_STARTED = 'TRANSACTION_REMOVE_STARTED';
export const TRANSACTION_REMOVE_COMPLETED = 'TRANSACTION_REMOVE_COMPLETED';
export const TRANSACTION_REMOVE_FAILED = 'TRANSACTION_REMOVE_FAILED';
