export const TUTOR_FETCH_STARTED = 'TUTOR_FETCH_STARTED';
export const TUTOR_FETCH_COMPLETED = 'TUTOR_FETCH_COMPLETED';
export const TUTOR_FETCH_FAILED = 'TUTOR_FETCH_FAILED';

export const TUTOR_ADD_STARTED = 'TUTOR_ADD_STARTED';
export const TUTOR_ADD_COMPLETED = 'TUTOR_ADD_COMPLETED';
export const TUTOR_ADD_FAILED = 'TUTOR_ADD_FAILED';

export const TUTOR_REMOVE_STARTED = 'TUTOR_REMOVE_STARTED';
export const TUTOR_REMOVE_COMPLETED = 'TUTOR_REMOVE_COMPLETED';
export const TUTOR_REMOVE_FAILED = 'TUTOR_REMOVE_FAILED';

export const TUTOR_SELECTED = 'TUTOR_SELECTED';
export const TUTOR_DESELECTED = 'TUTOR_DESELECTED';